/* 
 * ModSharp
 * Copyright (C) 2023-2026 Kxnrl. All Rights Reserved.
 *
 * This file is part of ModSharp.
 * ModSharp is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * ModSharp is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ModSharp. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef CSTRIKE_TYPE_KEYVALUES_H
#define CSTRIKE_TYPE_KEYVALUES_H

#include "cstrike/type/Color32.h"
#include "logging.h"
#include "platform.h"

#include <cstddef>
#include <cstdint>

class CUtlBuffer;
class IFileSystem;
class IKeyValuesSystem;
class IKeyValuesErrorSpew;
class KeyValues;

using KeyValuesSymbolProc = bool (*)(const char*, void*);

class CKeyValues_Data
{
public:
    // Data type
    enum types_t
    {
        TYPE_NONE = 0,
        TYPE_STRING,
        TYPE_INT,
        TYPE_FLOAT,
        TYPE_PTR,
        TYPE_WSTRING,
        TYPE_COLOR,
        TYPE_UINT64,
        TYPE_COMPILED_INT_BYTE, // hack to collapse 1 byte ints in the compiled format
        TYPE_COMPILED_INT_0,    // hack to collapse 0 in the compiled format
        TYPE_COMPILED_INT_1,    // hack to collapse 1 in the compiled format
        TYPE_NUMTYPES,
    };

protected:
#ifdef PLATFORM_WINDOWS
    MS_CLASS_IMPORT const char* Internal_GetName() const;
    MS_CLASS_IMPORT KeyValues*  Internal_GetSubKey() const;
#endif
    MS_CLASS_IMPORT const char* Internal_GetString(const char* defaultValue, char* pszOut, size_t maxlen);

private:
    union {
        int            m_iValue;
        float          m_flValue;
        void*          m_pValue;
        unsigned char  m_Color[4];
        uintptr_t      m_uValue;
        const char*    m_sValue;
        const wchar_t* m_wsValue;
        KeyValues*     m_pSub;
    };

    void* m_pUnk;

    uint32_t m_iKeyNameCaseSensitive : 24;
    uint32_t m_iDataType : 3;
    uint32_t m_bHasEscapeSequences : 1;
    uint32_t m_bAllocatedExternalMemory : 1;
    uint32_t m_bKeySymbolCaseSensitiveMatchesCaseInsensitive : 1;
    uint32_t m_bStoredSubKey : 1;
};

#pragma pack(push, 1)
class KeyValues : public CKeyValues_Data
{
public:
    MS_CLASS_IMPORT KeyValues(const char* setName, IKeyValuesSystem* kvsystem = nullptr, bool unkState = false);
    MS_CLASS_IMPORT ~KeyValues();

    MS_CLASS_IMPORT bool LoadFromBuffer(const char* resourceName, const char* pBuffer, IFileSystem* pFileSystem = nullptr, const char* pPathID = nullptr, KeyValuesSymbolProc pfnEvaluateSymbolProc = nullptr, IKeyValuesErrorSpew* pErrorSpew = nullptr, void* pUnk1 = nullptr, const char* pUnk2 = nullptr);
    MS_CLASS_IMPORT bool LoadFromBuffer(const char* resourceName, CUtlBuffer& buf, IFileSystem* pFileSystem = nullptr, const char* pPathID = nullptr, KeyValuesSymbolProc pfnEvaluateSymbolProc = nullptr, IKeyValuesErrorSpew* pErrorSpew = nullptr, void* pUnk1 = nullptr, const char* pUnk2 = nullptr);

    MS_CLASS_IMPORT void SetName(const char* name);
#ifdef PLATFORM_WINDOWS
    const char* GetName() const { return Internal_GetName(); }
#else
    MS_CLASS_IMPORT const char* GetName() const;
#endif

    MS_CLASS_IMPORT KeyValues* FindKey(const char* keyName, bool bCreate = false);
    MS_CLASS_IMPORT const KeyValues* FindKey(const char* keyName) const;

    MS_CLASS_IMPORT KeyValues* AddKey(const char* keyName); // creates a new key, with an autogenerated name.  name is guaranteed to be an integer, of value 1 higher than the highest other integer key name

#ifdef PLATFORM_WINDOWS
    KeyValues* GetFirstSubKey() { return Internal_GetSubKey(); }
#else
    MS_CLASS_IMPORT KeyValues* GetFirstSubKey();
#endif
    MS_CLASS_IMPORT KeyValues* FindLastSubKey();
    MS_CLASS_IMPORT bool FindAndDeleteSubKey(const char* name);

    MS_CLASS_IMPORT KeyValues* GetNextKey();

    MS_CLASS_IMPORT KeyValues* GetFirstTrueSubKey();
    MS_CLASS_IMPORT KeyValues* GetNextTrueSubKey();

    MS_CLASS_IMPORT KeyValues* GetFirstValue(); // When you get a value back, you can use GetX and pass in NULL to get the value.
    MS_CLASS_IMPORT KeyValues* GetNextValue();

    MS_CLASS_IMPORT int GetInt(const char* keyName = nullptr, int defaultValue = 0) const;
    MS_CLASS_IMPORT uint64_t GetUint64(const char* keyName = nullptr, unsigned long long defaultValue = 0) const;
    MS_CLASS_IMPORT float GetFloat(const char* keyName = nullptr, float defaultValue = 0.0f) const;

    const char* GetString(const char* keyName, const char* defaultValue = "", char* pszOut = nullptr, size_t maxlen = 0)
    {
        auto* key = FindKey(keyName);
        return key ? key->Internal_GetString(defaultValue, pszOut, maxlen) : defaultValue;
    }
    MS_CLASS_IMPORT void* GetPtr(const char* keyName = nullptr, void* defaultValue = nullptr) const;
    MS_CLASS_IMPORT Color GetColor(const char* keyName = nullptr, const Color& defaultColor = Color(0, 0, 0, 0)) const;
    bool        GetBool(const char* keyName = nullptr, bool defaultValue = false) const { return GetInt(keyName, defaultValue ? 1 : 0) ? true : false; }
    MS_CLASS_IMPORT bool IsEmpty(const char* keyName = nullptr) const;

    MS_CLASS_IMPORT void SetString(const char* keyName, const char* value);
    MS_CLASS_IMPORT void SetInt(const char* keyName, int value);
    MS_CLASS_IMPORT void SetUint64(const char* keyName, unsigned long long value);
    MS_CLASS_IMPORT void SetFloat(const char* keyName, float value);
    MS_CLASS_IMPORT void SetPtr(const char* keyName, void* value);
    MS_CLASS_IMPORT void SetColor(const char* keyName, Color value);
    void SetBool(const char* keyName, bool value) { SetInt(keyName, value ? 1 : 0); }

    MS_CLASS_IMPORT KeyValues* MakeCopy() const;
    MS_CLASS_IMPORT void Clear();

    MS_CLASS_IMPORT bool LoadFromFile(IFileSystem* file_system, const char* filename, const char* path_id, KeyValuesSymbolProc callback = nullptr, void* pUnk1 = nullptr, const char* pUnk2 = nullptr);
    MS_CLASS_IMPORT bool SaveToFile(IFileSystem* file_system, const char* filename, const char* path_id, bool allow_empty_string = false, bool binary_write = true);
    MS_CLASS_IMPORT void RecursiveSaveToFile(CUtlBuffer& buf, int indent, bool sort, bool allow_empty_string) const;

    MS_CLASS_IMPORT CKeyValues_Data::types_t GetDataType(const char* name) const;

private:
    KeyValues* m_pPeer; // pointer to next key in list
};
#pragma pack(pop)

#endif